# Generated by Django 5.0.1 on 2024-01-15 11:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_direction', models.IntegerField(null=True)),
                ('name', models.CharField(max_length=50, null=True)),
                ('sort', models.IntegerField()),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='BookChapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter_num', models.PositiveSmallIntegerField(null=True)),
                ('chapter_name', models.CharField(max_length=50, null=True)),
                ('word_count', models.PositiveIntegerField(null=True)),
                ('is_vip', models.PositiveIntegerField(null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='AuthorInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField(null=True)),
                ('invite_code', models.CharField(max_length=20)),
                ('pen_name', models.CharField(max_length=20)),
                ('chat_account', models.JSONField()),
                ('status', models.PositiveSmallIntegerField(default=0)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('work_direction', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='novel.bookcategory')),
            ],
        ),
        migrations.CreateModel(
            name='BookContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('chapter_id', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='novel.bookchapter')),
            ],
        ),
        migrations.CreateModel(
            name='BookInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic_url', models.CharField(max_length=200, null=True)),
                ('book_name', models.CharField(max_length=50)),
                ('author_name', models.CharField(max_length=50, null=True)),
                ('book_desc', models.CharField(max_length=200, null=True)),
                ('score', models.PositiveSmallIntegerField(null=True)),
                ('book_status', models.PositiveSmallIntegerField(null=True)),
                ('visit_count', models.PositiveBigIntegerField(null=True)),
                ('word_count', models.IntegerField(null=True)),
                ('comment_count', models.IntegerField(null=True)),
                ('last_chapter_id', models.PositiveBigIntegerField(null=True)),
                ('last_chapter_name', models.CharField(max_length=50, null=True)),
                ('last_chapter_update_time', models.DateTimeField(null=True)),
                ('is_vip', models.PositiveSmallIntegerField(null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('author_id', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='novel.authorinfo')),
                ('category_id', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='novel.bookcategory')),
            ],
        ),
        migrations.CreateModel(
            name='BookComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_content', models.CharField(max_length=512)),
                ('reply_count', models.PositiveIntegerField(null=True)),
                ('audit_status', models.PositiveSmallIntegerField(null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('last_comment_id', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='last_comment', to='novel.bookcomment')),
                ('next_comment_id', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='next_comment', to='novel.bookcomment')),
                ('user_id', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='novel.authorinfo')),
                ('book_id', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='novel.bookinfo')),
            ],
        ),
        migrations.AddField(
            model_name='bookchapter',
            name='book_id',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='novel.bookinfo'),
        ),
    ]
