# Generated by Django 5.0.1 on 2024-01-13 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novel', '0002_remove_bookinfo_author_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookchapter',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
